# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/https://api.practicemed.org/*"
  to = "https://api.practicemed.org"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
